[options]
addons_path = /mnt/extra-addons/custom/own
data_dir = /var/lib/odoo

# It allows you to manage multiple databases
list_db = True

; Automatic module reloading (ideal for development)
dev_mode = True
auto_reload = True

db_maxconn = 64

log_level = info
debug_mode = True